{% set name = "tabulate" %}
{% set version = "0.8.5" %}
{% set sha256 = "d0097023658d4dea848d6ae73af84532d1e86617ac0925d1adf1dd903985dac3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - tabulate = tabulate:_main

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - tabulate

  commands:
    - tabulate --help

about:
  home: https://github.com/astanin/python-tabulate
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Pretty-print tabular data in Python, a library and a command-line utility.'
  dev_url: https://github.com/astanin/python-tabulate

extra:
  recipe-maintainers:
    - jakirkham
    - synapticarbors
