travis:
  secure:
    BINSTAR_TOKEN: a3yHbEiSKbQquujYyUF/TIMUa+mv2PrYV7X7EyZSo2Nxu4xNKW5MyroDP5e+WcTBjcmYHvBVZXMnVWHiKfTmvF+ipQLYHOdMBUkaZK3D8azWj4jN2X5+qmit0iHtHRZsyIxpLlpgKagNR2z8iitP8MZmW8oJxNWOj0ddwFldaRbGPWG8r/Zb+ztuLBld5dl8fQBx2iZ0RzMb7xFmUWdwL0wsAdrq5hF16TjQ/iSGSSQ7GhkT08rqMjF1QvkpElm1SgWZDs8pMD8eQQW6bY+Wwworpu0/c3KtBWnoRXMGm/LVRj7GW8fHoLf0pNKDbKki1MXSTujI/vyYYaxY4MhejKn/lTq/Gs+EL/shFrtnXJLdQIy/zTC7L0QJJbQtnHuB8POw0xfQ52rtMVaEEIcrkhovexOnv3iZ2dRWSOIx89WNQvOFTGws9SzO9v9zgSXTBWKXSnYMIwSz9qNLhab2AcjYZZkc4ZO/G1HLFrxJnzlvgQJPKcyWfFPGS4tfi2sMByMGYIoL2Uwu800T2u383uS+ryOZ9RebDKdU379OgQNPejbe3si8txce2Jp+8O2CWC+ULxC1j3nzbqqgfoahkmq836OFX0kmCzBK9wDLVdL2eam7VzYBJyZ6QReXTc9bMXaSRwzuW4jtfwNX0QuqoFNago1ZdEe1yJXrQerncVM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
